# Generated by Django 6.0.5 on 2026-05-12 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('cupon', 'Cupón de descuento'), ('producto', 'Producto físico'), ('digital', 'Recompensa digital'), ('donacion', 'Donación benéfica'), ('experiencia', 'Experiencia'), ('mascota', 'Accesorio EcoBot'), ('insignia', 'Insignia especial')], max_length=20)),
                ('costo_puntos', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=1, help_text='0 = ilimitado')),
                ('imagen', models.CharField(help_text='Ruta en assets/rewards/', max_length=100)),
                ('descuento', models.PositiveIntegerField(default=0, help_text='Porcentaje si es cupón')),
                ('codigo', models.CharField(blank=True, help_text='Código de canje', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['costo_puntos'],
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_gastados', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('codigo_canje', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='marketplace.recompensa')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'ordering': ['-created_at'],
            },
        ),
    ]
