services:
  - type: web
    name: sensoria-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.13
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sensoria-db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false

databases:
  - name: sensoria-db
    plan: free