# Generated by Django 6.0.5 on 2026-06-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario normal'), ('collector', 'Recolector')], default='user', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
