# Generated by Django 6.0.5 on 2026-05-12 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('plastico', 'Plástico'), ('vidrio', 'Vidrio'), ('papel', 'Papel'), ('carton', 'Cartón'), ('metal', 'Metal'), ('organico', 'Orgánico'), ('electronico', 'Electrónico'), ('textil', 'Textil'), ('peligroso', 'Peligroso'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_base', models.PositiveIntegerField(default=10)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono en Flutter', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Escaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='escaneos/')),
                ('modo', models.CharField(choices=[('online', 'Online - IA en servidor'), ('offline', 'Offline - IA local')], default='online', max_length=10)),
                ('confianza_ia', models.FloatField(blank=True, help_text='Porcentaje de confianza de la IA (0-100)', null=True)),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0)),
                ('sincronizado', models.BooleanField(default=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to=settings.AUTH_USER_MODEL)),
                ('residuo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to='recycling.residuo')),
            ],
            options={
                'verbose_name': 'Escaneo',
                'verbose_name_plural': 'Escaneos',
                'ordering': ['-created_at'],
            },
        ),
    ]
