# Generated by Django 6.0.5 on 2026-05-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil'), ('legendario', 'Legendario')], default='facil', max_length=15)),
                ('tipo_objetivo', models.CharField(choices=[('escaneos_totales', 'Total de escaneos'), ('categoria_especifica', 'Categoría específica'), ('puntos', 'Puntos acumulados'), ('dias_consecutivos', 'Días consecutivos')], max_length=30)),
                ('objetivo_cantidad', models.PositiveIntegerField(help_text='Ej: 50 escaneos, 1000 puntos')),
                ('categoria_objetivo', models.CharField(blank=True, help_text="Solo si el tipo es 'categoria_especifica'", max_length=20)),
                ('puntos_recompensa', models.PositiveIntegerField(default=100)),
                ('badge_recompensa', models.CharField(blank=True, help_text='Nombre del badge en assets', max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto'), ('leyenda', 'Leyenda')], default='principiante', max_length=20)),
                ('icono', models.CharField(help_text='Ruta del badge: assets/badges/...', max_length=100)),
                ('condicion_tipo', models.CharField(choices=[('escaneos_totales', 'Total de escaneos'), ('categoria_especifica', 'Categoría específica'), ('puntos', 'Puntos acumulados'), ('dias_consecutivos', 'Días consecutivos')], max_length=30)),
                ('condicion_cantidad', models.PositiveIntegerField()),
                ('condicion_categoria', models.CharField(blank=True, max_length=20)),
                ('puntos_recompensa', models.PositiveIntegerField(default=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MisionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('escanear', 'Escanear residuos'), ('categoria', 'Escanear categoría específica'), ('puntos', 'Ganar puntos'), ('compartir', 'Compartir logro')], max_length=20)),
                ('objetivo_cantidad', models.PositiveIntegerField(default=3)),
                ('categoria_objetivo', models.CharField(blank=True, max_length=20)),
                ('puntos_recompensa', models.PositiveIntegerField(default=30)),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Misión Diaria',
                'verbose_name_plural': 'Misiones Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueado_en', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'unique_together': {('usuario', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('recompensa_obtenida', models.BooleanField(default=False)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso Desafío',
                'verbose_name_plural': 'Progresos Desafíos',
                'unique_together': {('usuario', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.misiondiaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso Misión',
                'verbose_name_plural': 'Progresos Misiones',
                'unique_together': {('usuario', 'mision')},
            },
        ),
    ]
